In [0]:
# from google.colab import files
# uploaded = files.upload()

In [0]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error 
#data reading
df=pd.read_csv("diabetes.csv")  
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
x1=df
y1=x1.pop("Outcome")

In [0]:
x1_tr,x1_te,y1_train,y1_test=train_test_split(x1,y1,test_size=0.3,random_state=0)

train_status=x1.describe()
train_status=train_status.transpose()
def norm(x):
  return(x-train_status['mean'])/train_status['std'];
x1_train=norm(x1_tr)
x1_test=norm(x1_te)

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
%tensorflow_version 1.x

In [0]:
def build_model():
  model=keras.Sequential([
                          layers.Dense(64,activation=tf.nn.relu,input_shape=[len(x1_train.keys())]),
                          layers.Dense(64,activation=tf.nn.relu),
                          layers.Dense(1,activation=tf.nn.sigmoid)
  ])
  optimizer=tf.keras.optimizers.RMSprop(0.001)
  model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['binary_crossentropy'])
  return model
model=build_model()
model.summary()

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 64)                576
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65
=================================================================
Total params: 4,801
Trainable params: 4,801
Non-trainable params: 0
_________________________________________________________________

In [0]:
class Dots(keras.callbacks.Callback):
  def on_epoch_end(self,epoch,logs):
    if epoch%100==0: print('')
    print('.',end='')

EPOCHS=150
history=model.fit(x1_train,y1_train,epochs=EPOCHS,validation_split=0.2,verbose=0,callbacks=[Dots()])

hist=pd.DataFrame(history.history)
hist['epoch']=history.epoch
hist.tail()

....................................................................................................
..................................................

         loss  binary_crossentropy  val_loss  val_binary_crossentropy  epoch
145  0.134262             0.134262  1.107498                 1.107498    145
146  0.134438             0.134438  1.083517                 1.083516    146
147  0.132981             0.132981  1.097022                 1.097022    147
148  0.132280             0.132280  1.113698                 1.113698    148
149  0.132034             0.132034  1.111426                 1.111426    149

In [0]:
pred=model.predict(x1_test)
pred=[1 if y>=0.5 else 0 for y in pred]

In [0]:
yp=[1 if y==1 else 0 for y in y1_test]
yp

[1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0]

In [0]:
total=0
correct=0
wrong=0
for i in pred:
  total=total+1
  if(yp[i]==pred[i]):
    correct=correct+1
  else:
     wrong=wrong+1
print("total"+str(total))
print("Correct"+str(correct))
print("Wrong"+str(wrong))

total231
Correct231
Wrong0